### PR TITLE
update to nodejs 20

### PR DESCRIPTION
**Pull request by hopisaurus**
Update nodejs 16 to nodejs 20 following github actions deprecation.

### CODE REVIEW

**Comment by HatsuneMiku3939** [comment]
Hi. @hopisaurus 

Thanks to your first pull request. I'm very happy to your help.
Actions error seems to be related to node version update.

<details>
  <summary>Error: error:0308010C:digital envelope routines::unsupported</summary>

```
ncc: Version 0.22.3
ncc: Compiling file index.js
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:68:19)
    at Object.createHash (node:crypto:[13](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/7733960337/job/21092065703?pr=249#step:4:14)8:10)
    at hashOf (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:58216)
    at module.exports (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/index.js.cache.js:3:60642)
    at runCmd (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:47355)
    at 819 (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:44227)
    at __webpack_require__ (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:[16](https://github.com/HatsuneMiku3939/direnv-action/actions/runs/7733960337/job/21092065703?pr=249#step:4:17)9)
    at startup (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:339)
    at module.exports.8 (/home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:371)
    at /home/runner/work/direnv-action/direnv-action/node_modules/@zeit/ncc/dist/ncc/cli.js.cache.js:1:381 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```
</details>


Can you fix it?

**Comment by hopisaurus** [comment]
Updated to using `@vercel/ncc` latest version.

**Comment by hopisaurus** [comment]
Updated all other github action's to latest available versions to fix other warnings.

**Comment by hopisaurus** [comment]
Maybe should setup dependabot for those too -> https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot#enabling-dependabot-version-updates-for-actions

**Comment by HatsuneMiku3939** [comment]
thank you so much.

**Pull request merged**
